#Workspace Cargo.toml:
[dev-dependencies]
assert_cmd = "2"
predicates = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
similar = "2"
anyhow = "1"

[workspace]
members = ["crates/kdu-cli","crates/kdu-core","crates/kdu-parsers","crates/kdu-sym","crates/kdu-report","crates/kdu-taint"]
resolver = "2"
